services:
  - type: web
    name: rag-voice-app
    runtime: python
    plan: starter
    autoDeploy: true

    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt

    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT

    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: PROJECT_ID
        sync: false
      - key: LOCATION
        value: "us-central1"
      - key: COMPANY_NAME
        value: "Your Company"
      - key: SECRET_KEY
        generateValue: true
      - key: SUPERADMIN_OTP
        sync: false
